name: Generate LHM CSV Export

on:
  schedule:
    # Runs automatically at the start of every hour (e.g., 1:00, 2:00, 3:00)
    - cron: '0 * * * *' 
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Convert JSON to CSV
        run: python py/json_to_csv.py

      - name: Commit and Push CSV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add data/players.csv
          
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update LHM players.csv in data folder" && git push)
